FROM php:cli

ARG DOCKER_UID
ARG DOCKER_GID
RUN pecl install apcu

RUN apt-get update && \
apt-get install -y \
zlib1g-dev libzip-dev wget git

RUN docker-php-ext-install zip
RUN docker-php-ext-enable apcu

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --filename=composer --install-dir=/usr/local/bin \
    && php -r "unlink('composer-setup.php');"

RUN wget https://get.symfony.com/cli/installer -O - | bash && mv /root/.symfony/bin/symfony /usr/local/bin/symfony

RUN usermod -u $DOCKER_UID www-data && groupmod -g $DOCKER_GID www-data && chown -R www-data:www-data /var/www/

WORKDIR /var/www

RUN PATH=$PATH:/var/www/html/vendor/bin:bin
