version:  '3.7'

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - 5432:5432
    volumes:
      - ./docker/volumes/postgresql/database:/var/lib/postgresql
    nginx:
      image: nginx:1.15.3-alpine
      restart: on-failure
      depends_on:
        - php
      volumes:
        - './src/public:/var/www/html/public'
        - './docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
      ports:
        - "${NGINX_PORT}:80"
    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      restart: on-failure
      volumes:
        - ./apps/eclipse-phase:/var/www/html
      env_file:
        - .env
      user: ${LOCAL_USER}
    php-cli:
      build:
        context: .
        dockerfile: docker/php/Dockerfile-cli
      restart: on-failure
      volumes:
        - ./apps/eclipse-phase:/var/www/html
        - ./docker/php/Makefile:/var/www/Makefile
      env_file:
        - .env
      user: ${LOCAL_USER}

